Vagrant.configure("2") do |config|
    config.vm.provision "shell",
      inline: "sudo sed -i 's/^#PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config && systemctl restart sshd"
  
    config.vm.define "webserver" do |web|
      web.vm.hostname = "webserver"
      web.vm.box = "centos/7"
      web.vm.network "private_network", ip: "192.168.55.29"
    end

    config.vm.define "dbserver" do |db|
      db.vm.hostname = "dbserver"
      db.vm.box = "centos/7"
      db.vm.network "private_network", ip: "192.168.55.30"
    end

  end